# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20161202_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='dumb',
        ),
    ]
