# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_remove_record_dumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
